#home:
#  path: /
#  defaults: { _controller: 'AppBundle\Controller\DefaultController::indexAction' }
#  methods:  GET
#

current_date:
  path: /exchange-rates
  controller: App\Controller\ExchangeRatesController::index

user_date:
  path: /exchange-rates/{date}
  controller: App\Controller\ExchangeRatesController::index

call_api:
  path: /api/exchange-rates/{date}
  controller: App\Controller\ExchangeRatesController::api

setupcheck:
  path: /api/setup-check
  controller: App\Controller\DefaultController::setupCheck

index:
  path: /{wildcard}
  defaults: { _controller: App\Controller\DefaultController::index }
  requirements:
    wildcard: .*
  # controller: App\Controller\DefaultController::index
